from pathlib import Path
import xml.etree.ElementTree as E
root=Path(__file__).resolve().parents[1]
def edit(file, old,new):
 p=root/file; s=p.read_text(encoding='utf-8-sig');assert old in s,(file,old);p.write_text(s.replace(old,new),encoding='utf-8')
edit('src/server/Gameplay/ToolService.luau',"model:SetAttribute('Kind',id);model:SetAttribute('OwnerUserId',p.UserId)","model:SetAttribute('Kind',id);model:SetAttribute('EffectToken',token);model:SetAttribute('OwnerUserId',p.UserId)")
edit('src/server/Gameplay/ToolService.luau',"local projectile=Models.create('impact_urn');projectile.Name='UrnProjectile';projectile.Parent=effects", "local art=Models.create('impact_urn');local projectile=Instance.new('Model');projectile.Name='UrnProjectile';projectile:SetAttribute('ProjectileOwner',p.UserId)\n     for _,v in art:GetChildren()do v.Parent=projectile end;art:Destroy();projectile.PrimaryPart=projectile.Handle;projectile.Parent=effects")
edit('src/server/Gameplay/ToolService.luau',"end;projectile:Destroy();if root(p)then impact(p,finish,d.radius,24)end", "end;local valid=projectile.Parent~=nil;projectile:Destroy();if valid and root(p)then impact(p,finish,d.radius,24)end")
edit('src/server/Gameplay/ToolService.luau',"removeZones(p);status:clear(p,false);trials[p]=nil;casting[p]=nil", "removeZones(p);for _,v in effects:GetChildren()do if v:GetAttribute('ProjectileOwner')==p.UserId then v:Destroy()end end;status:clear(p,false);trials[p]=nil;casting[p]=nil")
edit('src/client/ToolPresentation.luau',"model.Name:match('_(.+)$')","model:GetAttribute('EffectToken')")
edit('src/client/ToolsInput.luau',"rows[id]={label=label,buy=buy,equip=eq};", "if Run:IsStudio()and(id=='jailer_chain'or id=='double_mirror')then\n   label.Size=UDim2.fromOffset(235,52);local trial=button(scroll,'Trial_'..id,'PRUEBA',UDim2.fromOffset(242,y+7),UDim2.fromOffset(88,40));trial.Activated:Connect(function()call('trial',id);call('hold',id)end)\n  end\n  rows[id]={label=label,buy=buy,equip=eq};")
edit('src/client/ToolsInput.luau',"local use=button(gui,'UseTool'", "local carrying=Instance.new('TextLabel');carrying.Name='CarryHint';carrying.Position=UDim2.new(.5,-200,1,-62);carrying.Size=UDim2.fromOffset(400,26);carrying.BackgroundTransparency=1;carrying.TextSize=13;carrying.TextColor3=Color3.fromRGB(220,212,185);carrying.Parent=gui\n local use=button(gui,'UseTool'")
edit('src/client/ToolsInput.luau',"local tool=p.Character and p.Character:FindFirstChildOfClass('Tool');use.Visible", "carrying.Text=if p:GetAttribute('StolenCurseUid')then 'ROBO: lleva la Curse a un pedestal propio y coloca.'else ''\n  local tool=p.Character and p.Character:FindFirstChildOfClass('Tool');use.Visible")
edit('src/server/Gameplay/ToolCommerce.luau',"local offer=C.Offers[offerId];local p=profiles:get(player)","if not player or typeof(offerId)~='string'or typeof(receiptId)~='string'or #receiptId<1 or #receiptId>110 then return false end\n  local offer=C.Offers[offerId];local p=profiles:get(player)")
edit('src/server/Gameplay/ToolCommerce.luau',"typeof(receipt.PurchaseId)~='string'", "typeof(receipt.PurchaseId)~='string'or typeof(receipt.PlayerId)~='number'or typeof(receipt.ProductId)~='number'")
edit('src/server/Gameplay/CurseService.luau', "local r=records[uid];local rt=runtime[uid];local root=rootOf(p);local source=r and bases:getBaseById(r.baseId)","local r=records[uid];local rt=runtime[uid];local root=rootOf(p);local source=r and bases:getBaseById(r.baseId)\n  local destination=bases:getBaseForPlayer(p);local owner=r and Players:GetPlayerByUserId(r.ownerUserId)\n  if not destination or not freeSlot(destination)or not owner or owner:GetAttribute('ProfileStatus')~='READY' or ownedCount(p)>=Config.MaximumOwnedCurses then self:cancelTheftReservation(uid);return false end")
edit('src/server/Gameplay/TheftService.luau',"ops[uid]=op;souls:notify(Players:GetPlayerByUserId(op.from),'Están robando una Curse. Puedes interrumpir el transporte.')", "ops[uid]=op;local owner=Players:GetPlayerByUserId(op.from);if owner then souls:notify(owner,'Están robando una Curse. Puedes interrumpir el transporte.')end")
# Native plugin is local source, not a downloaded dependency.
xml=E.Element('roblox',version='4');item=E.SubElement(xml,'Item',{'class':'Script','referent':'ToolsLedgerPlugin'});props=E.SubElement(item,'Properties');E.SubElement(props,'string',name='Name').text='StealACurseToolsLedger';E.SubElement(props,'ProtectedString',name='Source').text=(root/'tools/ToolsLedger.plugin.luau').read_text();E.ElementTree(xml).write(root/'tools/ToolsLedger.plugin.rbxmx',encoding='utf-8',xml_declaration=True)
print('Core fixes and native plugin saved')
